### ISSUE TITLE
DPL-266 - Warning for tapestation quants where concentration is below 5nM (C=M, V=4)

### ISSUE THREAD

**Issue by stevieing** [sanger/quanthub#146]
**User story**
The heron team will soon be swapping to an alternative quantification method for the pooled library tubes. The previous method (lightcycler qPCR) was accurate for weak samples but the new method (D5000 tapestation) cannot reliably quantify samples <5nM (after applying the *1.62 fudge factor in quanthub). We will change the heron clean-up to elute in a lower volume, this should increase the concentration and prevent pools <5nM being created. In the event that a pool <5nM does get quantified we need to warn the heron team that the quant method might not be perfect and they will need to perform an alternative QC before progressing. I was thinking this warning could either be added to quanthub at the point the data gets uploaded or to limber when the user scans the pool tube ready to create the normalised child tube.

**Who are the primary contacts for this story**
Ben F
**Relates to**
https://rt.sanger.ac.uk/Ticket/Display.html?id=742329

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] After a tapestation quant has been uploaded if a concentration is below 5nM there should be a warning about alternative QC
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
Closes RT742329

**Comment by KatyTaylor** [comment]
New design to show outliers and warnings at the same time:
<img width="331" alt="Screenshot 2022-02-15 at 14 56 42" src="https://user-images.githubusercontent.com/10407809/154087733-55224394-5f94-402c-83e2-d2195a809f84.png">
