### ISSUE TITLE
DPL-425 - As an R&D scientist I would like add Hi-C quants to quanthub to automate the process to reduce the time and effort taken to perform quants, persist the quants, support the pooling and reduce the chances for errors

### ISSUE THREAD

**Issue by stevieing** [sanger/quanthub#169]
**User story**
As an R&D scientist I would like add Hi-C quants to quanthub to automate the process to reduce the time and effort taken to perform quants, persist the quants, support the pooling and reduce the chances for errors

**Who are the primary contacts for this story**
Ben

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] the ability to download ng/ul concentrations in Limber for all plate types
- [x] Hi-C quants should be the same format as the standard plate reader

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
Ben and Abdul will test whether they can use the existing quants and functionality in Limber. They may need a slight adjustment.

**Comment by stevieing** [comment]
This has now changed scope. No need to change quanthub but to add functionality to Limber to download ng/ul concentrations for all plate types.

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
