### ISSUE TITLE
DPL-599 Change to Heron Quanthub process for tapestation output data

### ISSUE THREAD

**Issue by neilsycamore** [sanger/quanthub#202]
**Summary**
As Heron Lab. we are looking to use a different analysis method which gives an output text file which has a different data structure and will require a change to Quanthub.

**Story**
The data structure of the new Tapestation file assigns molarity to different peaks the software detects in our samples (Peak Molarity [nmol/l]).
The peaks are variable in size, but we always want the peak molarity of the right library size at approximately 600bp, and can ignore the other peak concentrations. The number of peaks present per sample also varies, so the text file won’t always have the concentration we want in a universal position in its structure.

**Requirement**
We would like to add a step to Quanthub that allows us to manually select the peaks we want to submit.

**Who are the primary contacts for this story**
Ben (bm21), Marios (mp37)

**Related RT request**
https://rt.sanger.ac.uk/Ticket/Display.html?id=762132
For referrence and examples of old/new output files (attached to story also)

**Comment by TWJW-SANGER** [comment]
The new output format is a result of using a different mode of TapeStation operation to find a number of peaks for each pool measured.

There will be a max of 5 pools in each csv. The first pool "Ladder" should be ignored.

It's seems likely that the peak closest to 600 bp should be the one selected for the QC calculated - however it was felt there still needed to be a human check involved to be sure. Adding this ability within QuantHub would greatly complicate the QuantHub UI and make this a large story.

An alternative to this is for the users to manually select the correct peak for each well and create a csv in the existing format for upload into Quanthub. While more fiddly if a manual check is needed anyway - this is not a lot more work for the users.

**Comment by stevieing** [comment]
Closed as not needed
