### ISSUE TITLE
DPL-612 As a Heron TL (Rory Y) I would like to apply a calibration curve to the Quanthub processing of Heron QC Tapestation data, instead of the existing multiplying factor so that  low concentrations do not fail sequencing.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/quanthub#205]
**User story**
As a Heron TL (Rory Y) I would like to apply a calibration curve to the Quanthub processing of Heron QC Tapestation data, instead of the existing multiplying factor so that  low concentrations do not fail sequencing..

**Who are the primary contacts for this story**
Rory Y
Adam M
Benjamin M
Marios P

**Who is the nominated tester for UAT**
Rory Y

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Concentration values imported from QuantHub are corrected using an interpolation on a calibration curve.

**Additional context**
Tapestation overestimates the DNA concentration of samples in a nonlinear fashion. The overestimate is worse for low DNA concentration samples, this leads to the teams incorrectly preparing the libraries for sequencing which then fails.
Current QuantHub tries to correct this with a multiplicative (fudge) factor, while this is better it is still not sufficient at low concentrations.
Replacing this multiplication factor with a calibration curve should resolve the issue.

Related RT ticket [#762132](https://rt.sanger.ac.uk/Ticket/Display.html?id=762132)

**Comment by sdjmchattie** [comment]
I have emailed Rory to ask for the specifications of the calibration curve required and to get clarification on how this should be applied across replicates.

**Comment by sdjmchattie** [comment]
The functionality to specify calibration curves has been added.  Rory says he should be able to get the curve criteria to us by the end of today.  I will be able to look into implementing the correct curve starting Wednesday next week.

**Comment by sdjmchattie** [comment]
The curve function has been provided now:

| variable | value        |
---------------------------
| min      | 3.786691804  |
| max      | 49.59950332  |
| n        | -3.723772214 |
| ec50     | 35.52127433  |

y = min+(max-min)/(1+10^(n*(log10(x)-log10(ec_50))))

![image](https://user-images.githubusercontent.com/1999241/216949486-5ad50425-660a-4cbd-95a7-d69508d3a997.png)

**Comment by sdjmchattie** [comment]
The curve provided was applied to data that had already been multiplied by 1.62 so we need to add the multiplier back in to the original curve formula.
