### ISSUE TITLE
DPL-890 - As developers we need to upgrade Quanthub to Vue 3 as Vue 2 is out of support in December 2023

### ISSUE THREAD

**Issue by stevieing** [sanger/quanthub#253]
**User story**
As developers we need to upgrade Quanthub to Vue 3 as Vue 2 is out of support in December 2023. This will mean there are no more security or feature upgrades and so this creates a security risk.

**Who are the primary contacts for this story**
Steve

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow. (Tasks must be done in order):
- [ ] Upgrade node to a supported version (>= 18)
- [ ] Remove webpack and replace it with Vite
- [ ] Replace Jest with Vitest
- [ ] Replace Bootstrap with in-house components and styling
- [ ] Upgrade to latest version of Vue 2
- [ ] Upgrade to Vue 3

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
It will make sense to break this story down into further stories.

**Comment by Sangeetha-Bheeman** [comment]
Created the below stories:

[DPL-890-1](https://github.com/sanger/quanthub/issues/256)
[DPL-890-2](https://github.com/sanger/quanthub/issues/257)
[DPL-890-3](https://github.com/sanger/quanthub/issues/258)

**Comment by stevieing** [comment]
Closed as done
