### ISSUE TITLE
GPL-245	As a R&D lead for quant hub (Scott Goodwin) I would like automated outlier handling algorithm to have a fast auditable process to recover from gross errors.

### ISSUE THREAD

**Issue by rl15** [sanger/quanthub#74]
Change current algorithm (Scott will supply math)
New algorithm to be used for qPCR only (Suggestion this is managed through configuration in planning meeting)
In GUI 
highlight the outliers "flag up the individual wells which have been determined to be outliers rather than flagging up all replicates. " (Goodwin, October 4, 2019 at 2:14:45 PM GMT+)
Warn user that process is using automate outlier handling

**Comment by stevieing** [comment]
mad.js
create a library with a mad function which can accept a variable number of copy counts and will returns the values with a flag to indicate which ones are outliers.

**Comment by stevieing** [comment]
Modify the configuration so that the values that are sent to sequencescape cna be modified based on the quant type.

**Comment by stevieing** [comment]
Modify the presentation so that we can highlight specific outlier wells rather than highlighting the replicate.

**Comment by stevieing** [comment]
Providing transparent documentation which can be used for audit purposes and if possible autogenerate it.

**Comment by stevieing** [comment]
Research how to build documentation at deployment.

**Comment by stevieing** [comment]
Refactor the resulting two calculation libraries to abstract out any common behaviour.

**Comment by stevieing** [comment]
Refactor the way replicates are calculated so that it can cope with mad and cv calculations

**Comment by stevieing** [comment]
2. Refactor the replicates.js library to use calculations.js. Remove guards.
DONE
