### ISSUE TITLE
GPL-310 Sample Management - calculate averages in Quanthub because

### ISSUE THREAD

**Issue by harrietc52** [sanger/quanthub#77]
**User story**
As a Sample Management user I would like to see the averages calculated in Quanthub on a replicate set to avoid having to visit Sequencescape. 

**Who the primary contacts are for this story**
Danni Weldon

**Acceptance criteria**
To be considered successful the solution must allow:
1 - Averages are visible in Quanthub 

**Additional context**
Clarify where in Quanthub user would like this to be visible. Options being a 'Preview' button. Further enhancement is #78

**Comment by stevieing** [comment]
Closed as out of dat and no longer needed.
