### ISSUE TITLE
GPL-311 highlight samples for ukb becuase

### ISSUE THREAD

**Issue by harrietc52** [sanger/quanthub#78]
**User story**
As a sample management lead, I would like the replicate samples that have an average below 0.5 to be highlighted, for UK Biobank samples only, so we can report them back to the SSR

**Who the primary contacts are for this story**
Danni Weldon

**Acceptance criteria**
To be considered successful the solution must allow:
1 - A UKBiobank sample with average below 0.5 units is highlighted 

**Additional context**
Check which value is below 0.5 units
Consult output (CSV/request) to SS which currently sends the average, and use this to display the (preview) average

**Comment by stevieing** [comment]
UKB project is finished.
